services:
  postgres:
    image: postgres:17
    container_name: talentarc-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: talentarc

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    container_name: talentarc-backend

    restart: unless-stopped

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    container_name: talentarc-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres_data:
